version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-browsers
    steps:
      - checkout
      - run:
          name: dependencies
          command: mvn dependency:go-offline
      - run:
          name: spotlessCheck
          command: mvn spotless:apply
      - run:
          name: compile
          command: mvn compile
      - run:
          name: test
          command: mvn test
      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/adessoKicker.jar
